import { getHostBridge } from '../bridge'

/** TS mirror of the backend's `MediaEntry` — same deliberate boundary-naming
 * split Navigation uses for `NativeWindow` → `WindowInfo`. */
export interface ScreenshotEntry {
  path: string
  name: string
  /** `created().unwrap_or(modified)` — sort key and date-search source. */
  createdAt: number
  modifiedAt: number
  /** `"image"` or `"video"`. */
  kind: 'image' | 'video'
  ocrText: string | null
  /** A cached preview-frame JPEG for a video entry, generated by the
   *  background index sweep — `null` for images (rendered straight from
   *  `path`) and for a video not yet swept, with no thumbnail tool
   *  available, or whose extraction failed. */
  thumbnailPath: string | null
  /** Exempts this entry from the storage-duration trash sweep. */
  pinned: boolean
}

export type ScreenshotPasteFormat = 'auto' | 'image' | 'file' | 'path'

export interface ScreenshotsSettings {
  searchScopes: string[]
  videoExtensions: string[]
  gridColumns: number
  ocrEnabled: boolean
  pasteFormat: ScreenshotPasteFormat
  /** `"unlimited"` or a day-count string — how long a screenshot file is
   *  kept before the background sweep moves it to the OS trash. */
  storageDuration: string
}

/** The Screenshots settings pane's fields (`ScreenshotsPane.tsx`, which
 *  stays native) — read live, same reasoning as `getNotesSettings`. */
export async function getScreenshotsSettings(): Promise<ScreenshotsSettings> {
  return (await getHostBridge().call('host.screenshots.getSettings')) as unknown as ScreenshotsSettings
}

/** Scans every configured scope, newest-first, joined with whatever OCR
 *  text/video thumbnails the background sweep has indexed so far — also
 *  kicks that sweep, matching native `list_screenshots`. */
export async function queryScreenshots(): Promise<ScreenshotEntry[]> {
  return ((await getHostBridge().call('host.screenshots.query')) ?? []) as ScreenshotEntry[]
}

/** Hides the palette, then copies+pastes `path` using an explicit format. */
export async function pasteScreenshotWithFormat(path: string, format: ScreenshotPasteFormat): Promise<void> {
  await getHostBridge().call('host.screenshots.pasteWithFormat', { path, format })
}

/** Copies `path` to the clipboard using an explicit format — no palette hide. */
export async function copyScreenshotWithFormat(path: string, format: ScreenshotPasteFormat): Promise<void> {
  await getHostBridge().call('host.screenshots.copyWithFormat', { path, format })
}

/** Hides the palette, then delivers `path` to whatever window is under the
 *  mouse pointer as a synthesized drag-and-drop drop. */
export async function dropScreenshot(path: string): Promise<void> {
  await getHostBridge().call('host.screenshots.drop', { path })
}

/** Whether "Drop at Cursor" is available on this platform/session (X11
 *  Linux only today — XDND has no equivalent on Wayland/macOS/Windows). */
export async function screenshotDropSupported(): Promise<boolean> {
  return (await getHostBridge().call('host.screenshots.dropSupported')) === true
}

export async function openScreenshot(path: string): Promise<void> {
  await getHostBridge().call('host.screenshots.open', { path })
}

/** Pastes the most recently created screenshot image using the configured
 *  default format. Resolves `found: false` (rather than throwing) when
 *  there are none, so the caller can show its own toast. */
export async function pasteLatestScreenshot(): Promise<{ found: boolean }> {
  return (await getHostBridge().call('host.screenshots.pasteLatest')) as { found: boolean }
}

/** Drops the most recently created screenshot image at the cursor. Same
 *  `{ found }` shape as `pasteLatestScreenshot`. */
export async function dropLatestScreenshot(): Promise<{ found: boolean }> {
  return (await getHostBridge().call('host.screenshots.dropLatest')) as { found: boolean }
}

/** Exempts (or re-includes) `path` from the storage-duration trash sweep. */
export async function setScreenshotPinned(path: string, pinned: boolean): Promise<void> {
  await getHostBridge().call('host.screenshots.setPinned', { path, pinned })
}
