//! Detects the [nspasteboard.org](https://nspasteboard.org) convention —
//! `org.nspasteboard.ConcealedType`/`TransientType`/`AutoGeneratedType` —
//! that password managers (1Password, Bitwarden, the system Keychain
//! autofill, ...) and most other macOS clipboard managers (Raycast,
//! Alfred, Paste, CleanShot, ...) already respect: a copy carrying one of
//! these flavors is explicitly marked "don't record this," most commonly
//! a password. `clipboard_watcher.rs`'s own `suppress_text` only covers
//! *this app's own* extensions asking not to be recorded
//! (`Clipboard.copy(..., { concealed: true })`) — it has no way to know a
//! *third-party* app just copied a password, which is the actual common
//! case this exists to catch. Found live: copying a value with
//! `org.nspasteboard.ConcealedType` set (exactly what a real password
//! manager does) was recorded into history unfiltered.
//!
//! macOS-only — Windows has its own, unrelated convention
//! (`CF_EXCLUDECLIPBOARDCONTENTFROMMONITOR`) and Linux clipboard managers
//! have no comparably established standard; `is_marked_sensitive` is a
//! safe `false` everywhere else so the watcher's call site doesn't need
//! per-platform branching.

#[cfg(target_os = "macos")]
pub fn is_marked_sensitive() -> bool {
    use objc2_app_kit::NSPasteboard;
    use objc2_foundation::NSString;

    let Some(types) = NSPasteboard::generalPasteboard().types() else { return false };
    ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        .iter()
        .any(|flavor| types.containsObject(&NSString::from_str(flavor)))
}

#[cfg(not(target_os = "macos"))]
pub fn is_marked_sensitive() -> bool {
    false
}
